### ISSUE TITLE
TM vision exporting

### ISSUE THREAD

**Issue by WUPENGDENG** [TechmanRobotInc/tmr_ros2#11]
I want use my PC to receive image from TM robot. Can I finish the work without ROS?

**Comment by TechmanRobotIncOwner** [comment]
YES, in TMflow, in Network Service, users can upload logs, robot data, and **vision images** to a remote host on a timely basis with multiple connections and accounts.

To go to Network Service, navigate to ≡≡, and click System > Network Service.
