### ISSUE TITLE
[TM_WARN] TM_COM: Connection timeout

### ISSUE THREAD

**Issue by victorbillaud** [TechmanRobotInc/tmr_ros2#7]
Hello,

I have a problem with my connexion, i don't understand, im following all the tutorial (https://github.com/TechmanRobotInc/tmr_ros2) and my connexion doesn't work. 
Can you explain me ?

![image](https://user-images.githubusercontent.com/61359041/114407101-5e124a00-9ba8-11eb-9724-c08afca27525.png)

**Comment by guanyewtan** [comment]
Hi! I usually face this error when I forget to run the TM program, is the TM program running in the listen node?
If you see the line 'data table is correct' but with the connection error:

![image](https://user-images.githubusercontent.com/42372488/114495246-5312f480-9c50-11eb-8c0a-c003047b36f1.png)

It probably means your connection is set up correctly but the TM program isn't started/is not in the listen node.

If the 'data table is correct' line isn't there then it might be an issue with the connection setup.

**Comment by victorbillaud** [comment]
Hello,

Thanks for you answer. I don’t know what is the problem but i think i run
the program correctly and i can ping the robot.
There is something special to do on TM Flow ?

**Comment by victorbillaud** [comment]
Thanks for your answer, I don't see anything like that on log.
Im working on ros-dashing (ubuntu 18.04)

**Comment by victorbillaud** [comment]
Look my log this morning. Im retrying on ros-melodic.
![image](https://user-images.githubusercontent.com/61359041/114517774-f3601d80-9c3e-11eb-98cb-7435788a4ac3.png)

**Comment by daan-schepers** [comment]
These are the exact same issues i'm running up against. The connection is made, I'm able to ping the cobot's address and can also use the image_talker node. 

But my hardware is a Raspberry Pi 4, so I thought it has something to do with the arm-processor. Currently testing with a Ubuntu based laptop, but have not had any succes either...

**Comment by guanyewtan** [comment]
Not sure if this helps but my Ethernet cable is connected here: 
![2C9DF033-C0BB-42C9-8012-28FCFFC56A63](https://user-images.githubusercontent.com/42372488/115011151-dba7c400-9ee0-11eb-8a57-f557c0da5fef.jpeg)

I'm using a virtual machine to run Linux but I had to change the ipv4 setting in windows network settings. Next week I'm gonna be setting up another Linux system so I'll take note of the steps I took and see if I encounter the same problem 😅

**Comment by daan-schepers** [comment]
@guanyewtan is right, you need to connect through that specific ethernetport because it is configured for Modbus. Some commando's (like setting IO's) go via modbus, thus they won't work on the other point. (except when you give the commando's via socket only)

But @victorbillaud, The trick is to configure all the network setting like in the tutorial, then restart the cobot, then start the tm_driver node. In my setup it works every time like this. Sadly kind of a hassle, but the cobot needs to start up with your ROS machine in the same network lane.

**Comment by janandries** [comment]
are you sure that the Ethernet Slave is enabled in the TM Flow (Settings >> Connection >> Ethernet Slave)? 
I have the problem that the robot doesn't always start up with that enabled, i think when it can't find a ethernet connection during boot, it will turn it off.
